"""Add id_number_hash to KYC

Revision ID: e7f8g9h0i1j2
Revises: a1b2c3d4e5f6
Create Date: 2026-04-29 03:44:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f8g9h0i1j2'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_records', sa.Column('id_number_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_kyc_records_id_number_hash'), 'kyc_records', ['id_number_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_records_id_number_hash'), table_name='kyc_records')
    op.drop_column('kyc_records', 'id_number_hash')
    # ### end Alembic commands ###
